### ISSUE TITLE
数据集和模型

### ISSUE THREAD

**Issue by AllofLife** [hnndweige/weeds-recognize#1]
您好，我想学习下这个项目，方便给个模型和数据集吗

**Comment by hnndweige** [comment]
https://github.com/AlexOlsen/DeepWeeds

**Comment by AllofLife** [comment]
谢谢

**Comment by hnndweige** [comment]
https://github.com/AlexOlsen/DeepWeeds
记得帮我点个星哦😏

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: raozhufa ***@***.***&gt;
发送时间: 2022年4月8日 21:05
收件人: hnndweige/weeds-recognize ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [hnndweige/weeds-recognize] 数据集和模型 (Issue #1)





 
您好，我想学习下这个项目，方便给个模型和数据集吗
